#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  statefork_configure.sh --host <ssh-host> [options]
  statefork_configure.sh --local [options]
  statefork_configure.sh

Options:
  --config <path>                 Local config path. Default: ~/.statefork-skill.env
  --install-root <path>           Linux-side install root override.
  --statefork-root <path>         Linux-side StateFork repo path override.
  --waypoint-root <path>          Linux-side Waypoint repo path override.
  --work-root <path>              Linux-side project workspace root override.
  --statefork-repo-url <url>      StateFork git URL override.
  --waypoint-repo-url <url>       Waypoint git URL override.
  --bootstrap                     Run statefork_bootstrap.sh after writing config.
  -h, --help                      Show this help.

Leave path options unset to use Linux-side defaults under $HOME/statefork-agent.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${STATEFORK_SKILL_CONFIG:-$HOME/.statefork-skill.env}"
ORIGINAL_ARGC="$#"

if [ -f "$CONFIG" ]; then
  # shellcheck disable=SC1090
  . "$CONFIG"
fi

HOST="${STATEFORK_HOST:-}"
LOCAL="${STATEFORK_LOCAL:-0}"
BOOTSTRAP=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host)
      HOST="${2:-}"
      LOCAL=0
      shift 2
      ;;
    --local)
      HOST=""
      LOCAL=1
      shift
      ;;
    --config)
      CONFIG="${2:-}"
      shift 2
      ;;
    --install-root)
      STATEFORK_INSTALL_ROOT="${2:-}"
      shift 2
      ;;
    --statefork-root)
      STATEFORK_ROOT="${2:-}"
      shift 2
      ;;
    --waypoint-root)
      WAYPOINT_ROOT="${2:-}"
      shift 2
      ;;
    --work-root)
      STATEFORK_WORK_ROOT="${2:-}"
      shift 2
      ;;
    --statefork-repo-url)
      STATEFORK_REPO_URL="${2:-}"
      shift 2
      ;;
    --waypoint-repo-url)
      WAYPOINT_REPO_URL="${2:-}"
      shift 2
      ;;
    --bootstrap)
      BOOTSTRAP=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf '[FAIL] Unknown argument: %s\n' "$1" >&2
      usage
      exit 2
      ;;
  esac
done

ask() {
  local prompt="$1"
  local default="$2"
  local reply
  if [ -n "$default" ]; then
    printf '%s [%s]: ' "$prompt" "$default" >&2
  else
    printf '%s: ' "$prompt" >&2
  fi
  IFS= read -r reply
  if [ -n "$reply" ]; then
    printf '%s' "$reply"
  else
    printf '%s' "$default"
  fi
}

if [ "$ORIGINAL_ARGC" -eq 0 ] && [ -t 0 ] && [ -z "${STATEFORK_HOST:-}" ] && [ "$LOCAL" != "1" ] && [ -z "$HOST" ]; then
  target="$(ask 'SSH target for the Linux VM; leave blank only when Codex is already running on Linux' '')"
  if [ -n "$target" ]; then
    HOST="$target"
    LOCAL=0
  else
    LOCAL=1
  fi
fi

if [ "$ORIGINAL_ARGC" -eq 0 ] && [ -t 0 ]; then
  STATEFORK_INSTALL_ROOT="${STATEFORK_INSTALL_ROOT:-}"
  STATEFORK_ROOT="${STATEFORK_ROOT:-}"
  WAYPOINT_ROOT="${WAYPOINT_ROOT:-}"
  STATEFORK_WORK_ROOT="${STATEFORK_WORK_ROOT:-}"
  STATEFORK_REPO_URL="${STATEFORK_REPO_URL:-}"
  WAYPOINT_REPO_URL="${WAYPOINT_REPO_URL:-}"

  STATEFORK_INSTALL_ROOT="$(ask 'Linux install root override; blank uses $HOME/statefork-agent on that host' "$STATEFORK_INSTALL_ROOT")"
  STATEFORK_ROOT="$(ask 'Linux StateFork repo path override; blank uses <install-root>/StateFork' "$STATEFORK_ROOT")"
  WAYPOINT_ROOT="$(ask 'Linux Waypoint repo path override; blank uses <install-root>/Waypoint' "$WAYPOINT_ROOT")"
  STATEFORK_WORK_ROOT="$(ask 'Linux project work root override; blank uses <install-root>/work' "$STATEFORK_WORK_ROOT")"
  STATEFORK_REPO_URL="$(ask 'StateFork git URL override; blank uses the skill default' "$STATEFORK_REPO_URL")"
  WAYPOINT_REPO_URL="$(ask 'Waypoint git URL override; blank uses the skill default' "$WAYPOINT_REPO_URL")"
fi

if [ "$LOCAL" != "1" ] && [ -z "$HOST" ]; then
  cat <<EOF >&2
[FAIL] No target selected.

Use one of:
  $0 --host user@linux-vm
  $0 --local

You can also configure later by creating ~/.statefork-skill.env manually.
EOF
  exit 2
fi

shell_quote() {
  printf "'"
  printf "%s" "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

write_export() {
  local key="$1"
  local value="$2"
  [ -n "$value" ] || return 0
  printf 'export %s=' "$key"
  shell_quote "$value"
  printf '\n'
}

mkdir -p "$(dirname "$CONFIG")"
{
  printf '# StateFork skill local config generated by statefork_configure.sh\n'
  printf '# This file is read on the machine running Codex.\n'
  if [ "$LOCAL" = "1" ]; then
    printf 'export STATEFORK_LOCAL=1\n'
    printf 'unset STATEFORK_HOST\n'
  else
    printf 'unset STATEFORK_LOCAL\n'
    write_export STATEFORK_HOST "$HOST"
  fi
  write_export STATEFORK_INSTALL_ROOT "${STATEFORK_INSTALL_ROOT:-}"
  write_export STATEFORK_ROOT "${STATEFORK_ROOT:-}"
  write_export WAYPOINT_ROOT "${WAYPOINT_ROOT:-}"
  write_export STATEFORK_WORK_ROOT "${STATEFORK_WORK_ROOT:-}"
  write_export STATEFORK_REPO_URL "${STATEFORK_REPO_URL:-}"
  write_export WAYPOINT_REPO_URL "${WAYPOINT_REPO_URL:-}"
  write_export STATEFORK_REPO_FALLBACKS "${STATEFORK_REPO_FALLBACKS:-}"
  write_export WAYPOINT_REPO_FALLBACKS "${WAYPOINT_REPO_FALLBACKS:-}"
} > "$CONFIG"

printf '[OK] StateFork local config written: %s\n' "$CONFIG"

if [ "$BOOTSTRAP" -eq 1 ]; then
  "$SCRIPT_DIR/statefork_bootstrap.sh"
fi
